#pragma once

#define InputFolderW		L"#inputFolder"
#define OutputFolderW		L"#outputFolder"
#define LogFilePathW		L"#log"
#define CreateIndexW		L"#indexing"
#define IdPrefixW			L"#idPrefix"
#define IdSuffixW			L"#idSuffix"
#define PerformOCW			L"#oc"
#define UnitScaleFactorW	L"#usf"
#define SkinLevelNsmW		L"#skinLevel"
#define IsYAxisUpW			L"#isYAxisUp"
#define ReferenceLonLatW	L"#referenceLonLat"
#define MeshTypeW			L"#meshType"
#define AlignToCenterW		L"#alignToCenter"
#define EpsgW				L"#epsg"

#define ProgramPath		"programPath"
#define InputFolder		"#inputFolder"
#define OutputFolder	"#outputFolder"
#define LogFilePath		"#log"
#define CreateIndex		"#indexing"
#define IdPrefix		"#idPrefix"
#define IdSuffix		"#idSuffix"
#define PerformOC		"#oc"
#define UnitScaleFactor	"#usf"
#define SkinLevelNsm	"#skinLevel"
#define IsYAxisUp		"#isYAxisUp"
#define ReferenceLonLat	"#referenceLonLat"
#define MeshType		"#meshType"
#define AlignToCenter	"#alignToCenter"
#define Epsg			"#epsg"
